name: label-sponsor

on:
  issues:
    types:
      - 'opened'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set sponsor label
        uses: JasonEtco/is-sponsor-label-action@39d88e461a53ecb1b3c0a13673e6252f9976f2f5
        with:
          label: ":sparkling_heart: sponsor"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
